<h1 class="text-center">Add products</h1>
<form action="/product/add" method="post">
    <div class="form-group">
        <label for="exampleInput">Email name</label>
        <input type="text" name="pname" class="form-control"
         id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter name">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Email category</label>
        <input type="text" name="category" class="form-control"
         id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter category">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Email price</label>
        <input type="number" name="price" class="form-control"
         id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter price">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Email quantity</label>
        <input type="number" name="quantity" class="form-control"
         id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter name">
    </div>

    <button type="submit" class="btn btn-info">Submit</button>
</form>